# Generated by Django 3.2.7 on 2021-11-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(upload_to='')),
                ('image_3', models.ImageField(upload_to='')),
                ('image_4', models.ImageField(upload_to='')),
                ('image_5', models.ImageField(upload_to='')),
                ('image_6', models.ImageField(upload_to='')),
                ('image_7', models.ImageField(upload_to='')),
                ('image_8', models.ImageField(upload_to='')),
                ('image_9', models.ImageField(upload_to='')),
                ('image_10', models.ImageField(upload_to='')),
                ('image_11', models.ImageField(upload_to='')),
                ('image_12', models.ImageField(upload_to='')),
                ('image_13', models.ImageField(upload_to='')),
                ('image_14', models.ImageField(upload_to='')),
                ('image_15', models.ImageField(upload_to='')),
                ('image_16', models.ImageField(upload_to='')),
                ('image_17', models.ImageField(upload_to='')),
                ('image_18', models.ImageField(upload_to='')),
                ('image_19', models.ImageField(upload_to='')),
                ('image_20', models.ImageField(upload_to='')),
            ],
        ),
    ]
