# Generated by Django 3.2.7 on 2021-11-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='image_1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_10',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_11',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_12',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_13',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_14',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_15',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_16',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_17',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_18',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_19',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_20',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_5',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_6',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_7',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_8',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='image_9',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
