# Generated by Django 3.2.7 on 2021-11-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_people_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_11',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_12',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_13',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_14',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_15',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_16',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_17',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_18',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_19',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_20',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image_9',
        ),
        migrations.AddField(
            model_name='people',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='height',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='job',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
